In [ ]:
### tensor is a flexible data structure that hold data in a variety of different ways.
#### dimensionality of tensor, scalar: no dimension, vector: single dimension, 
#### types of tensor. Variables: tf.Variable("Hello", tf.string), Constants: tf.constant([1,2,3])
#### tensor charactoristic. Shape: tf.Tensor([4 6], shape = (2,), dtype=int32)

In [1]:
import tensorflow as tf

In [2]:

model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape = (1, ))])


2022-01-06 08:47:59.328893: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-01-06 08:47:59.329457: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-06 08:47:59.330869: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
model.variables # kernel = weight in NN
# shape = (1, 1) -> 2 dimensions
# numpy -> randomly initialized value


[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.31948078]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [9]:
vector = tf.Variable(initial_value = [1,2])
print(vector)
vector = tf.Variable([1,2], dtype=tf.float32)
print(vector)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [12]:
tensor = tf.constant([1,2,3,4,5,6], shape = (2,3)) # can reshape the tensor constant
print(tensor)
tensor = tf.constant(-1, shape = [2,3])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-1 -1 -1]
 [-1 -1 -1]], shape=(2, 3), dtype=int32)


In [13]:
## tensor operations

In [ ]:
tf.add([1,2], [3,4])
tf.square(5)
tf.reduce_sum([1,2,3])
tf.square(2) + tf.square(3)

In [14]:
# eager execution in tensorflow: Evaluate values immediately, Broadcasting support, Operator overloading, Numpy compatibility

In [16]:
# evaluating values
x = 2 
x_squared = tf.square(x)
print("{}".format(x_squared))
print(x_squared)

4
tf.Tensor(4, shape=(), dtype=int32)


In [18]:
a = tf.constant([[1,2], [3,4]])
tf.add(a, 1)
a ** 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [19]:
# Examin custom layers
class MyLayer(tf.keras.layers.Layer):

    def __init__(self):
        super(MyLayer, self).__init__()
        self.my_var = tf.Variable(100)
        self.my_other_var_list = [tf.Variable(x) for x in range(2)]

m = MyLayer()
[variable.numpy() for variable in m.variables]

[100, 0, 1]