In [3]:
import tensorflow as tf
import numpy as np
import random

In [4]:
x_train = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype = float)
y_train = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype = float)

w = tf.Variable(random.random(), trainable = True)
b = tf.Variable(random.random(), trainable = True)


2022-01-06 10:34:24.980275: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-01-06 10:34:24.980578: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-06 10:34:24.981556: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [6]:
def simple_loss (real_y, pred_y):
    return tf.abs(real_y - pred_y)

LEARNING_RATE = 0.001

In [ ]:
def fit_data(real_x, real_y):
    with tf.GradientTape(persistent=True) as tape:
        # Make prediction
        pred_y = w * real_x + b 
        # calculate loss
        reg_loss = simple_loss(real_y, pred_y)

    # calculate gradients
    w_gradient = tape.gradient(reg_loss, w)
    b_gradient = tape.gradient(reg_loss, b)

    # update variables
    w.assign_sub(w_gradient * LEARNING_RATE) # assign_sub : Substraction and assign the result
    b.assign_sub(b_gradient * LEARNING_RATE)

In [ ]:
for _ in range(500):
    fit_data(x_train, y_train)



In [7]:
# Gradient Descent with tf.GradientTape

In [ ]:
def train_step(images, labels):
    with tf.GradientTape() as tape:
        logits = model(images, training=True)
        loss_value = loss_object(labels, logits) # logits = raw prediction values for each category
    loss_history.append(loss_value.numpy().mean())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

In [8]:
# Gradient compuatation in Tensorflow
# loss만 정해주면 Gradient tape이 Gradient를 구해준다.

In [9]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
    loss = w * w

tape.gradient(loss, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [10]:
# compute gradients of higher ranked tensors

In [16]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.square(y)
    # derivative of z wrt the original input tensor x
    dz_dx = t.gradient(z, x)
dz_dx

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [26]:
x = tf.Variable(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x * x
    z = y * y 
    dz_dx = t.gradient(z, x)
    dy_dx = t.gradient(y, x)
del t
print(dz_dx, dy_dx)


tf.Tensor(108.0, shape=(), dtype=float32) tf.Tensor(6.0, shape=(), dtype=float32)


In [21]:
# higher order gradients

In [33]:
x = tf.Variable(1.0)

with tf.GradientTape(persistent=True) as tape_2:
    with tf.GradientTape(persistent=False) as tape_1:
        y = x * x * x

    dy_dx = tape_1.gradient(y,x)
    print(dy_dx)
d2y_dx2 = tape_2.gradient(dy_dx, x)
print(d2y_dx2)

assert dy_dx.numpy() == 3.0
assert d2y_dx2.numpy() == 6.0

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
